; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
upload_protocol = picotool
monitor_speed = 115200
board_build.core = earlephilhower
lib_deps =
	adafruit/Adafruit TLC5947@^1.2.3
	fastled/FastLED@^3.10.1
	bblanchon/ArduinoJson@^7.4.2
build_flags =
  -DUSE_TINYUSB
  -DCFG_TUSB_CONFIG_FILE=\"tusb_config_custom.h\"
  -Iinclude/
